name: cli
description: A sample command-line application.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  http: ^1.3.0
  command_runner:
    path: ../command_runner
  wikipedia:
    path: ../wikipedia
  logging: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
